// 批改提示词模板
import type { Question, ReferenceAnswer, StudentAnswer } from '../../../stores/useExamDataStore'

// 加载静态模板
export async function loadStaticPromptTemplate(): Promise<any> {
  try {
    // 尝试直接导入开发环境
    try {
      const promptModule = await import('../../../config/prompt.json')
      return promptModule.default || promptModule
    } catch (importError) {
      // 生产环境回退到fetch
      const response = await fetch('/src/config/prompt.json')
      if (!response.ok) {
        throw new Error(`Failed to load prompt.json: ${response.status}`)
      }
      return await response.json()
    }
  } catch (error) {
    console.error('加载静态提示词模板失败:', error)
    throw new Error('Failed to load static prompt template')
  }
}

// 构建基础批改提示词
export function buildGradingPrompt(
  question: Question,
  referenceAnswer: ReferenceAnswer,
  studentAnswer: StudentAnswer,
  staticPrompt: any,
): string {
  return`${staticPrompt.role}

${staticPrompt.task_description}

QUESTION:
${question.question}

REFERENCE ANSWER:
${referenceAnswer.answer}

GRADING RULES:
${JSON.stringify(staticPrompt.grading_rules, null, 2)}

SCORING POLICY:
${staticPrompt.scoring_policy}

OUTPUT FORMAT:
${JSON.stringify(staticPrompt.output_format.structure, null, 2)}

STUDENT ANSWER:
${studentAnswer.answer}
Maximum score for this question: ${question.score}

IMPORTANT: Replace the null values in the output format with:
- student_id: ${studentAnswer.student_id}
- question_id: ${question.question_id}
- Student answer: 100% identical to the student's original text.
- matched reference answer: actual matched the reference answer from the student's answer, and the text in quotes must be an exact excerpt from the reference answer.
- Scoring Point: actual matched the scoring point from the reference answer(must be a number). If a student's answer matches multiple scoring points, break it down and write it separately, with each scoring point being only one digit.
- reason: Must follow the format "Reason(scoring point X):YOUR_REASON". YOUR_REASON should be a concise explanation generated by the LLM.
- total_score: actual calculated score (must be a number)
Please evaluate the student answer and return the JSON response according to the format above.`
}

// 构建理由生成提示词
export function buildReasonGenerationPrompt(
  question: Question,
  referenceAnswer: ReferenceAnswer,
  studentAnswer: StudentAnswer,
  highlightedText: string,
  highlightType: 'correct' | 'wrong' | 'unclear' | 'redundant',
): string {
  return `You are a university computer science instructor providing detailed feedback on student answers.

TASK: Generate a detailed scoring reason for the highlighted text segment.

QUESTION:
${question.question}

REFERENCE ANSWER:
${referenceAnswer.answer}

STUDENT ANSWER:
${studentAnswer.answer}

HIGHLIGHTED TEXT: "${highlightedText}"

CLASSIFICATION: ${highlightType}

REASON FORMAT:
"Reason(scoring point X):YOUR_REASON"

Please provide a clear and specific reason explaining why this text segment is classified as "${highlightType}".

The reason should:
1. Reference specific aspects of the reference answer when applicable
2. Explain the scoring decision clearly
3. Be concise but comprehensive
4. Use educational language appropriate for student feedback
5. The reason should be concise and to the point, and should not be too long.
Return only the reason text, ensure string format, no additional formatting or labels.`
}

// 构建Few-Shot批改提示词
export function buildGradingPromptWithFewShot(
  question: Question,
  referenceAnswer: ReferenceAnswer,
  studentAnswer: StudentAnswer,
  staticPrompt: any,
  fewShotPrompt: string,
): string {
  // 如果没有few-shot示例，直接返回基础prompt
  if (!fewShotPrompt.trim()) {
    return buildGradingPrompt(question, referenceAnswer, studentAnswer, staticPrompt)
  }

  // 构建带Few-Shot的完整prompt
  return `${staticPrompt.role}

${staticPrompt.task_description}

QUESTION:
${question.question}

REFERENCE ANSWER:
${referenceAnswer.answer}

GRADING RULES:
${JSON.stringify(staticPrompt.grading_rules, null, 2)}

SCORING POLICY:
${staticPrompt.scoring_policy}

${fewShotPrompt}

STUDENT ANSWER:
${studentAnswer.answer}

OUTPUT FORMAT:
${JSON.stringify(staticPrompt.output_format.structure, null, 2)}

IMPORTANT: Replace the null values in the output format with:
- student_id: ${studentAnswer.student_id}
- question_id: ${question.question_id}
- Student answer: 100% identical to the student's original text.
- Scoring Point: actual matched the scoring point from the reference answer(must be a number). If a student's answer matches multiple scoring points, break it down and write it separately, with each scoring point being only one digit.
- matched reference answer: actual matched the reference answer from the student's answer, and the text in quotes must be an exact excerpt from the reference answer.
- reason: Must follow the format "Reason(scoring point X):YOUR_REASON". YOUR_REASON should be a concise explanation generated by the LLM.
- total_score: actual calculated score (must be a number)
Please evaluate the student answer and return the JSON response according to the format above.`
}

// 提示词模板
export const GRADING_PROMPTS = {
  /**
   * 标准单个学生给分
   */
  SINGLE_STUDENT_GRADING: buildGradingPrompt,

  /**
   * 带Few-Shot示例的学生给分
   */
  FEW_SHOT_STUDENT_GRADING: buildGradingPromptWithFewShot,

  /**
   * 老师标记高亮自动生成评分理由
   */
  HIGHLIGHT_REASON_GENERATION: buildReasonGenerationPrompt,
}

